export const SUBJECTS = [
  "Mathematics",
  "Physics",
  "Computer Science",
  "Biology",
  "Chemistry",
  "Economics",
  "Data Science",
  "Machine Learning"
];

const subjectApplications = {
  Mathematics: ["Model quantitative relationships", "Build scientific and computational methods"],
  Physics: ["Predict physical systems", "Connect measurement with mathematical models"],
  "Computer Science": ["Design reliable software", "Reason about computation and scale"],
  Biology: ["Explain living systems", "Connect molecular mechanisms to organisms and ecosystems"],
  Chemistry: ["Predict matter and reactions", "Design materials, medicines, and processes"],
  Economics: ["Analyze choices and institutions", "Evaluate policy and market outcomes"],
  "Data Science": ["Learn from data", "Quantify evidence and uncertainty"],
  "Machine Learning": ["Build predictive systems", "Train models that generalize"]
};

const subjectAccents = {
  Mathematics: "violet",
  Physics: "blue",
  "Computer Science": "coral",
  Biology: "mint",
  Chemistry: "gold",
  Economics: "coral",
  "Data Science": "blue",
  "Machine Learning": "mint"
};

function concept({
  id,
  title,
  subject,
  difficulty,
  definition,
  prerequisites = [],
  relatedTerms = [],
  formulaTex = "",
  application = "",
  example = "",
  frontierExtensions = [],
  subjects = [subject]
}) {
  return {
    id,
    title,
    subject,
    subjects,
    difficulty,
    shortDefinition: definition,
    detailedExplanation: `${definition} The important step is to understand what the objects are, how they relate, and which assumptions make the idea valid. This concept becomes especially useful when it is connected to its prerequisites and applied in a concrete system.`,
    prerequisites,
    relatedTerms,
    applications: application
      ? [application, ...subjectApplications[subject]]
      : subjectApplications[subject],
    formulaTex,
    examples: [
      example || `Use ${title.toLowerCase()} to describe a small real or simulated system, then test what changes when one assumption is varied.`
    ],
    deeperConcepts: [],
    frontierExtensions,
    sources: [
      {
        type: "Reference",
        label: `${title} overview`,
        url: `https://en.wikipedia.org/wiki/${encodeURIComponent(title.replaceAll(" ", "_"))}`
      },
      {
        type: "Video",
        label: `${title} lectures`,
        url: `https://www.youtube.com/results?search_query=${encodeURIComponent(`${title} lecture`)}`
      }
    ],
    minutes: difficulty === "beginner" ? 6 : difficulty === "intermediate" ? 9 : difficulty === "advanced" ? 12 : 15,
    accent: subjectAccents[subject]
  };
}

export const mathematics = [
  concept({ id: "numbers", title: "Numbers and Arithmetic", subject: "Mathematics", difficulty: "beginner", definition: "Numbers represent quantity, order, and magnitude, while arithmetic defines operations on them.", relatedTerms: ["algebra", "probability"], formulaTex: "a+b=b+a", example: "Compare additive growth with multiplicative growth in a savings balance." }),
  concept({ id: "algebra", title: "Algebra", subject: "Mathematics", difficulty: "beginner", definition: "Algebra uses symbols and rules to express relationships and solve for unknown quantities.", prerequisites: ["numbers"], relatedTerms: ["functions", "linear-algebra"], formulaTex: "ax+b=0 \\Rightarrow x=-\\frac{b}{a}", application: "Translate verbal constraints into equations.", example: "Solve for the time needed when distance equals speed multiplied by time." }),
  concept({ id: "functions", title: "Functions", subject: "Mathematics", difficulty: "beginner", definition: "A function maps each allowed input to exactly one output.", prerequisites: ["algebra"], relatedTerms: ["data-structures", "regression"], formulaTex: "f:X\\to Y,\\quad y=f(x)", application: "Represent how one quantity depends on another.", example: "Temperature can be modeled as a function of position and time." }),
  concept({ id: "limits", title: "Limits and Continuity", subject: "Mathematics", difficulty: "intermediate", definition: "A limit describes the value a function approaches as its input approaches a point.", prerequisites: ["functions"], relatedTerms: ["derivatives", "probability-distributions"], formulaTex: "\\lim_{x\\to a}f(x)=L", example: "Approximate instantaneous speed using smaller and smaller time intervals." }),
  concept({ id: "derivatives", title: "Derivatives", subject: "Mathematics", difficulty: "intermediate", definition: "A derivative measures instantaneous change and the local slope of a function.", prerequisites: ["limits"], relatedTerms: ["gradient-descent", "kinematics"], formulaTex: "f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}", application: "Measure rates, sensitivities, and optimization directions.", example: "Velocity is the derivative of position with respect to time." }),
  concept({ id: "integrals", title: "Integrals", subject: "Mathematics", difficulty: "intermediate", definition: "An integral accumulates infinitesimal contributions over an interval or region.", prerequisites: ["limits"], relatedTerms: ["probability-distributions", "energy"], formulaTex: "\\int_a^b f(x)\\,dx", application: "Compute total change, area, mass, and probability.", example: "Integrate velocity over time to recover displacement." }),
  concept({ id: "vectors", title: "Vectors", subject: "Mathematics", difficulty: "beginner", definition: "A vector represents a quantity with components, often interpreted as magnitude and direction.", prerequisites: ["algebra"], relatedTerms: ["momentum", "embeddings"], formulaTex: "\\mathbf{v}=(v_1,\\ldots,v_n)", example: "Represent wind using horizontal and vertical velocity components." }),
  concept({ id: "linear-algebra", title: "Linear Algebra", subject: "Mathematics", difficulty: "intermediate", definition: "Linear algebra studies vectors, matrices, linear transformations, and vector spaces.", prerequisites: ["vectors", "algebra"], relatedTerms: ["neural-networks", "quantum-mechanics"], formulaTex: "A\\mathbf{x}=\\mathbf{b}", application: "Transform data and solve coupled systems.", example: "A matrix rotates image coordinates or mixes features in a neural network." }),
  concept({ id: "multivariable-calculus", title: "Multivariable Calculus", subject: "Mathematics", difficulty: "advanced", definition: "Multivariable calculus extends derivatives and integrals to functions with several inputs.", prerequisites: ["derivatives", "integrals", "vectors"], relatedTerms: ["gradient-descent", "electromagnetism"], formulaTex: "\\nabla f=\\left(\\frac{\\partial f}{\\partial x_1},\\ldots,\\frac{\\partial f}{\\partial x_n}\\right)", example: "The gradient points toward the steepest increase of a temperature field." }),
  concept({ id: "odes", title: "Ordinary Differential Equations", subject: "Mathematics", difficulty: "advanced", definition: "An ODE relates an unknown function of one independent variable to its derivatives.", prerequisites: ["derivatives", "integrals"], relatedTerms: ["oscillations", "population-dynamics"], formulaTex: "\\frac{dy}{dt}=f(t,y)", application: "Model change through time.", example: "Exponential population growth follows dy/dt = ry." }),
  concept({ id: "pdes", title: "Partial Differential Equations", subject: "Mathematics", difficulty: "advanced", definition: "A PDE relates a function of multiple variables to its partial derivatives.", prerequisites: ["odes", "multivariable-calculus"], relatedTerms: ["heat-equation", "waves", "electromagnetism"], formulaTex: "F(x,u,\\nabla u,\\nabla^2u)=0", application: "Model fields that vary across space and time.", example: "Pressure, temperature, and electromagnetic fields are described with PDEs." }),
  concept({ id: "boundary-conditions", title: "Boundary and Initial Conditions", subject: "Mathematics", difficulty: "advanced", definition: "Boundary and initial conditions specify the constraints needed to select a particular differential-equation solution.", prerequisites: ["odes"], relatedTerms: ["heat-equation", "experimental-design"], formulaTex: "u(x,0)=u_0(x),\\quad u|_{\\partial\\Omega}=g", example: "Fix the ends of a vibrating string and specify its starting shape." }),
  concept({ id: "heat-equation", title: "Heat Equation", subject: "Mathematics", subjects: ["Mathematics", "Physics"], difficulty: "advanced", definition: "The heat equation describes how a diffusing quantity spreads through space over time.", prerequisites: ["pdes", "boundary-conditions", "heat-transfer"], relatedTerms: ["fourier-analysis", "reaction-diffusion-biology", "diffusion-models"], formulaTex: "\\frac{\\partial u}{\\partial t}=\\alpha\\Delta u", application: "Model temperature, concentration, and diffusion.", example: "A hot spot on a metal plate gradually smooths into the surrounding material." }),
  concept({ id: "fourier-analysis", title: "Fourier Analysis", subject: "Mathematics", difficulty: "advanced", definition: "Fourier analysis decomposes signals and functions into oscillatory frequency components.", prerequisites: ["integrals", "linear-algebra", "heat-equation"], relatedTerms: ["waves", "signal-processing"], formulaTex: "\\hat f(\\xi)=\\int_{-\\infty}^{\\infty}f(x)e^{-2\\pi i x\\xi}\\,dx", application: "Solve PDEs and analyze signals.", example: "Represent a complex sound as a sum of simple sine waves." }),
  concept({ id: "stochastic-pdes", title: "Stochastic PDEs", subject: "Mathematics", difficulty: "frontier", definition: "A stochastic PDE combines spatial differential operators with random forcing or uncertain coefficients.", prerequisites: ["pdes", "probability-distributions", "stochastic-processes"], relatedTerms: ["diffusion-models", "statistical-mechanics"], formulaTex: "du=\\mathcal{L}u\\,dt+\\sigma(u)\\,dW_t", application: "Model noisy fields and random dynamics.", example: "Describe a diffusing concentration disturbed by microscopic fluctuations.", frontierExtensions: ["Regularity structures", "Stochastic quantization", "Neural operators"] })
];

export const physics = [
  concept({ id: "measurement-units", title: "Measurement and Units", subject: "Physics", difficulty: "beginner", definition: "Measurement compares physical quantities against agreed units and records uncertainty.", relatedTerms: ["descriptive-statistics", "experimental-design"], formulaTex: "[F]=MLT^{-2}", example: "Report a length with units and an uncertainty interval." }),
  concept({ id: "kinematics", title: "Kinematics", subject: "Physics", difficulty: "beginner", definition: "Kinematics describes position, velocity, and acceleration without yet explaining their causes.", prerequisites: ["functions", "measurement-units"], relatedTerms: ["derivatives", "newton-laws"], formulaTex: "v=\\frac{dx}{dt},\\quad a=\\frac{dv}{dt}", example: "Track the motion of a thrown ball over time." }),
  concept({ id: "newton-laws", title: "Newton's Laws", subject: "Physics", difficulty: "beginner", definition: "Newton's laws connect forces to changes in motion and define action-reaction pairs.", prerequisites: ["kinematics", "vectors"], relatedTerms: ["momentum", "odes"], formulaTex: "\\mathbf{F}=m\\mathbf{a}", example: "Predict how a cart accelerates when pushed with a known force." }),
  concept({ id: "energy", title: "Energy", subject: "Physics", difficulty: "beginner", definition: "Energy is a conserved quantity that tracks a system's capacity for change.", prerequisites: ["algebra"], relatedTerms: ["thermodynamics", "chemical-bonds"], formulaTex: "E_k=\\frac12 mv^2", example: "A falling object converts gravitational potential energy into kinetic energy." }),
  concept({ id: "momentum", title: "Momentum", subject: "Physics", difficulty: "intermediate", definition: "Momentum combines mass and velocity and is conserved in isolated systems.", prerequisites: ["vectors", "newton-laws"], relatedTerms: ["energy", "quantum-mechanics"], formulaTex: "\\mathbf{p}=m\\mathbf{v}", example: "Use momentum conservation to analyze a collision." }),
  concept({ id: "oscillations", title: "Oscillations", subject: "Physics", difficulty: "intermediate", definition: "Oscillations are repeated motions around an equilibrium produced by restoring forces and inertia.", prerequisites: ["odes", "newton-laws"], relatedTerms: ["waves", "fourier-analysis"], formulaTex: "\\frac{d^2x}{dt^2}+\\omega^2x=0", example: "A mass on a spring repeats its motion with a characteristic frequency." }),
  concept({ id: "waves", title: "Waves", subject: "Physics", difficulty: "advanced", definition: "Waves transport energy and information through spatially propagating disturbances.", prerequisites: ["oscillations", "pdes"], relatedTerms: ["fourier-analysis", "electromagnetism"], formulaTex: "\\frac{\\partial^2u}{\\partial t^2}=c^2\\nabla^2u", example: "A plucked string sends a disturbance toward both ends." }),
  concept({ id: "thermodynamics", title: "Thermodynamics", subject: "Physics", difficulty: "intermediate", definition: "Thermodynamics relates heat, work, energy, entropy, and macroscopic equilibrium.", prerequisites: ["energy", "probability"], relatedTerms: ["statistical-mechanics", "thermochemistry"], formulaTex: "dU=\\delta Q-\\delta W", example: "Analyze how compressing a gas changes its internal energy." }),
  concept({ id: "heat-transfer", title: "Heat and Diffusion", subject: "Physics", difficulty: "intermediate", definition: "Heat transfer describes energy flow caused by temperature differences through conduction, convection, and radiation.", prerequisites: ["thermodynamics", "derivatives"], relatedTerms: ["heat-equation", "chemical-kinetics"], formulaTex: "\\mathbf{q}=-k\\nabla T", example: "A metal spoon warms from the end placed in hot water." }),
  concept({ id: "electromagnetism", title: "Electromagnetism", subject: "Physics", difficulty: "advanced", definition: "Electromagnetism unifies electric and magnetic fields, charges, currents, and electromagnetic waves.", prerequisites: ["multivariable-calculus", "waves"], relatedTerms: ["electrochemistry", "networking"], formulaTex: "\\nabla\\cdot\\mathbf{E}=\\frac{\\rho}{\\varepsilon_0}", example: "A changing magnetic field induces an electric current." }),
  concept({ id: "quantum-mechanics", title: "Quantum Mechanics", subject: "Physics", difficulty: "advanced", definition: "Quantum mechanics describes physical systems using states, amplitudes, operators, and probabilistic measurement.", prerequisites: ["linear-algebra", "waves", "probability"], relatedTerms: ["quantum-chemistry", "information-theory"], formulaTex: "i\\hbar\\frac{\\partial}{\\partial t}|\\psi\\rangle=\\hat H|\\psi\\rangle", example: "A particle's state can be a superposition of position possibilities." }),
  concept({ id: "statistical-mechanics", title: "Statistical Mechanics", subject: "Physics", difficulty: "frontier", definition: "Statistical mechanics derives macroscopic behavior from probability distributions over microscopic states.", prerequisites: ["thermodynamics", "probability-distributions"], relatedTerms: ["stochastic-pdes", "metabolism"], formulaTex: "Z=\\sum_i e^{-\\beta E_i}", example: "Connect molecular motion to the temperature and pressure of a gas.", frontierExtensions: ["Nonequilibrium thermodynamics", "Renormalization group", "Active matter"] })
];

export const computerScience = [
  concept({ id: "algorithms", title: "Algorithms", subject: "Computer Science", difficulty: "beginner", definition: "An algorithm is a finite, precise procedure for transforming inputs into outputs.", prerequisites: ["functions"], relatedTerms: ["complexity", "optimization"], formulaTex: "T(n)=O(f(n))", example: "Sort a list by repeatedly comparing and rearranging elements." }),
  concept({ id: "data-structures", title: "Data Structures", subject: "Computer Science", difficulty: "beginner", definition: "Data structures organize information so operations can be performed efficiently.", prerequisites: ["algorithms"], relatedTerms: ["databases", "graphs-cs"], example: "Use a hash table for fast key lookup." }),
  concept({ id: "complexity", title: "Computational Complexity", subject: "Computer Science", difficulty: "intermediate", definition: "Complexity measures how time or memory requirements grow with input size.", prerequisites: ["algorithms", "functions"], relatedTerms: ["computability", "optimization"], formulaTex: "T(n)=O(n\\log n)", example: "Compare linear search with binary search as a list grows." }),
  concept({ id: "recursion", title: "Recursion", subject: "Computer Science", difficulty: "intermediate", definition: "Recursion solves a problem by reducing it to smaller instances of the same problem.", prerequisites: ["algorithms"], relatedTerms: ["trees", "dynamic-programming"], formulaTex: "T(n)=T(n-1)+c", example: "Traverse a folder by applying the same procedure to each subfolder." }),
  concept({ id: "graphs-cs", title: "Graphs and Networks", subject: "Computer Science", difficulty: "intermediate", definition: "A graph represents entities as vertices and relationships as edges.", prerequisites: ["data-structures"], relatedTerms: ["networking", "learning-graphs", "ecology"], formulaTex: "G=(V,E)", example: "Represent cities and roads, then find a shortest route." }),
  concept({ id: "programming-languages", title: "Programming Languages", subject: "Computer Science", difficulty: "intermediate", definition: "Programming language theory studies syntax, semantics, types, and ways to express computation.", prerequisites: ["algorithms"], relatedTerms: ["computability", "compilers"], example: "A type system prevents adding a number directly to a text string." }),
  concept({ id: "operating-systems", title: "Operating Systems", subject: "Computer Science", difficulty: "advanced", definition: "An operating system manages processes, memory, storage, and hardware resources.", prerequisites: ["data-structures", "programming-languages"], relatedTerms: ["distributed-systems", "networking"], example: "The scheduler shares CPU time among competing processes." }),
  concept({ id: "databases", title: "Databases", subject: "Computer Science", difficulty: "intermediate", definition: "Databases store structured information and support reliable querying and updates.", prerequisites: ["data-structures"], relatedTerms: ["data-engineering", "distributed-systems"], formulaTex: "\\pi_{name}(\\sigma_{score>90}(Students))", example: "Use an indexed table to retrieve a customer's orders." }),
  concept({ id: "networking", title: "Computer Networking", subject: "Computer Science", difficulty: "intermediate", definition: "Networking studies protocols that move data between communicating devices.", prerequisites: ["graphs-cs"], relatedTerms: ["distributed-systems", "electromagnetism"], example: "TCP retransmits missing packets to create a reliable byte stream." }),
  concept({ id: "distributed-systems", title: "Distributed Systems", subject: "Computer Science", difficulty: "advanced", definition: "Distributed systems coordinate computation across machines that can fail independently.", prerequisites: ["networking", "operating-systems", "databases"], relatedTerms: ["consensus", "cloud-computing"], formulaTex: "N\\ge 2f+1", example: "Replicate a database so service continues after a machine fails." }),
  concept({ id: "cryptography", title: "Cryptography", subject: "Computer Science", difficulty: "advanced", definition: "Cryptography uses mathematical constructions to protect confidentiality, integrity, and authenticity.", prerequisites: ["numbers", "algorithms", "probability"], relatedTerms: ["networking", "information-theory"], formulaTex: "c\\equiv m^e\\pmod n", example: "A digital signature lets others verify who signed a message." }),
  concept({ id: "computability", title: "Computability", subject: "Computer Science", difficulty: "frontier", definition: "Computability studies which problems can be solved by algorithms and which cannot.", prerequisites: ["algorithms", "programming-languages", "complexity"], relatedTerms: ["formal-logic", "machine-learning"], formulaTex: "HALT=\\{\\langle M,x\\rangle:M(x)\\downarrow\\}", example: "The halting problem proves that no program can decide termination for every program.", frontierExtensions: ["Interactive proofs", "Quantum complexity", "Algorithmic information theory"] })
];

export const biology = [
  concept({ id: "cells", title: "Cells", subject: "Biology", difficulty: "beginner", definition: "Cells are the fundamental organized units of living systems.", relatedTerms: ["metabolism", "cell-signaling"], example: "A membrane maintains different chemical conditions inside and outside a cell." }),
  concept({ id: "genetics", title: "Genetics", subject: "Biology", difficulty: "beginner", definition: "Genetics studies how biological information is inherited and varied.", prerequisites: ["cells"], relatedTerms: ["gene-expression", "population-genetics"], formulaTex: "P(Aa)=2pq", example: "Track how an allele can pass from parents to offspring." }),
  concept({ id: "evolution", title: "Evolution by Natural Selection", subject: "Biology", difficulty: "beginner", definition: "Evolution changes inherited traits in populations across generations.", prerequisites: ["genetics", "probability"], relatedTerms: ["ecology", "optimization"], formulaTex: "\\Delta \\bar z=\\frac{\\operatorname{Cov}(w_i,z_i)}{\\bar w}", example: "Antibiotic resistance rises when resistant bacteria reproduce more successfully." }),
  concept({ id: "proteins", title: "Proteins", subject: "Biology", difficulty: "intermediate", definition: "Proteins are folded amino-acid polymers that perform structural, catalytic, and signaling roles.", prerequisites: ["cells", "chemical-bonds"], relatedTerms: ["gene-expression", "organic-chemistry"], example: "An enzyme's shape lets it bind and transform a particular molecule." }),
  concept({ id: "metabolism", title: "Metabolism", subject: "Biology", difficulty: "intermediate", definition: "Metabolism is the network of chemical reactions that transforms matter and energy in organisms.", prerequisites: ["cells", "energy", "chemical-kinetics"], relatedTerms: ["thermodynamics", "systems-biology"], formulaTex: "\\Delta G=\\Delta H-T\\Delta S", example: "Cells couple energy-releasing reactions to energy-requiring synthesis." }),
  concept({ id: "gene-expression", title: "Gene Expression", subject: "Biology", difficulty: "intermediate", definition: "Gene expression converts encoded DNA information into functional RNA and proteins.", prerequisites: ["genetics", "proteins"], relatedTerms: ["cell-signaling", "neural-networks"], formulaTex: "DNA\\to RNA\\to Protein", example: "A regulatory protein changes how strongly a gene is transcribed." }),
  concept({ id: "cell-signaling", title: "Cell Signaling", subject: "Biology", difficulty: "advanced", definition: "Cell signaling transmits information through receptors and molecular response networks.", prerequisites: ["proteins", "gene-expression"], relatedTerms: ["feedback-control", "systems-biology"], example: "Insulin binding triggers a cascade that changes glucose uptake." }),
  concept({ id: "ecology", title: "Ecology", subject: "Biology", difficulty: "intermediate", definition: "Ecology studies relationships among organisms and their physical environments.", prerequisites: ["evolution"], relatedTerms: ["graphs-cs", "population-dynamics"], formulaTex: "\\frac{dN}{dt}=rN\\left(1-\\frac{N}{K}\\right)", example: "A food web links energy flow among interacting species." }),
  concept({ id: "population-dynamics", title: "Population Dynamics", subject: "Biology", difficulty: "advanced", definition: "Population dynamics models how births, deaths, movement, and interactions change populations.", prerequisites: ["ecology", "odes"], relatedTerms: ["epidemiology", "stochastic-processes"], formulaTex: "\\frac{dN}{dt}=rN-\\frac{r}{K}N^2", example: "Logistic growth slows as a population approaches carrying capacity." }),
  concept({ id: "population-genetics", title: "Population Genetics", subject: "Biology", difficulty: "advanced", definition: "Population genetics studies how selection, drift, mutation, and migration change allele frequencies.", prerequisites: ["genetics", "evolution", "probability-distributions"], relatedTerms: ["bayesian-inference", "ecology"], formulaTex: "p^2+2pq+q^2=1", example: "Genetic drift can fix an allele in a small population by chance." }),
  concept({ id: "systems-biology", title: "Systems Biology", subject: "Biology", difficulty: "advanced", definition: "Systems biology models interacting biological components as dynamic networks.", prerequisites: ["cell-signaling", "metabolism", "graphs-cs"], relatedTerms: ["odes", "causal-inference"], formulaTex: "\\frac{d\\mathbf{x}}{dt}=S\\mathbf{v}(\\mathbf{x})", example: "Model feedback among genes, proteins, and metabolites." }),
  concept({ id: "reaction-diffusion-biology", title: "Reaction-Diffusion in Biology", subject: "Biology", subjects: ["Biology", "Mathematics", "Chemistry"], difficulty: "frontier", definition: "Reaction-diffusion systems combine local biochemical reactions with spatial diffusion to produce patterns.", prerequisites: ["systems-biology", "heat-equation", "chemical-kinetics"], relatedTerms: ["morphogenesis", "stochastic-pdes"], formulaTex: "\\frac{\\partial \\mathbf{u}}{\\partial t}=D\\nabla^2\\mathbf{u}+\\mathbf{f}(\\mathbf{u})", example: "Interacting chemicals can create spots or stripes during development.", frontierExtensions: ["Morphogen gradients", "Synthetic pattern formation", "Spatial transcriptomics"] })
];

export const chemistry = [
  concept({ id: "atoms", title: "Atoms", subject: "Chemistry", difficulty: "beginner", definition: "Atoms consist of nuclei and electrons and are the basic units of chemical elements.", prerequisites: ["measurement-units"], relatedTerms: ["periodic-table", "quantum-mechanics"], example: "Carbon atoms share six protons but can contain different neutron counts." }),
  concept({ id: "periodic-table", title: "Periodic Table", subject: "Chemistry", difficulty: "beginner", definition: "The periodic table organizes elements by atomic number and recurring electronic properties.", prerequisites: ["atoms"], relatedTerms: ["chemical-bonds", "quantum-chemistry"], example: "Elements in the same column often form similar ions." }),
  concept({ id: "chemical-bonds", title: "Chemical Bonds", subject: "Chemistry", difficulty: "beginner", definition: "Chemical bonds arise from electron interactions that stabilize arrangements of atoms.", prerequisites: ["atoms", "periodic-table"], relatedTerms: ["proteins", "organic-chemistry"], formulaTex: "E_{bond}\\approx E_{products}-E_{reactants}", example: "Water's polar covalent bonds produce an uneven charge distribution." }),
  concept({ id: "stoichiometry", title: "Stoichiometry", subject: "Chemistry", difficulty: "beginner", definition: "Stoichiometry uses balanced reactions to relate amounts of reactants and products.", prerequisites: ["algebra", "atoms"], relatedTerms: ["chemical-equilibrium", "metabolism"], formulaTex: "n=\\frac{m}{M}", example: "Calculate oxygen needed to burn a known amount of methane." }),
  concept({ id: "thermochemistry", title: "Thermochemistry", subject: "Chemistry", difficulty: "intermediate", definition: "Thermochemistry studies heat and energy changes during chemical reactions.", prerequisites: ["energy", "stoichiometry"], relatedTerms: ["thermodynamics", "metabolism"], formulaTex: "\\Delta H=H_{products}-H_{reactants}", example: "Measure heat released by a combustion reaction." }),
  concept({ id: "chemical-kinetics", title: "Chemical Kinetics", subject: "Chemistry", difficulty: "intermediate", definition: "Chemical kinetics studies reaction rates and the mechanisms controlling them.", prerequisites: ["derivatives", "stoichiometry"], relatedTerms: ["heat-transfer", "reaction-diffusion-biology"], formulaTex: "r=k[A]^m[B]^n", example: "Increasing temperature accelerates many reactions by increasing successful collisions." }),
  concept({ id: "chemical-equilibrium", title: "Chemical Equilibrium", subject: "Chemistry", difficulty: "intermediate", definition: "Chemical equilibrium occurs when forward and reverse reaction rates balance.", prerequisites: ["chemical-kinetics", "thermochemistry"], relatedTerms: ["acids-bases", "optimization"], formulaTex: "K=\\frac{[C]^c[D]^d}{[A]^a[B]^b}", example: "Adding reactant shifts an equilibrium mixture toward products." }),
  concept({ id: "acids-bases", title: "Acids and Bases", subject: "Chemistry", difficulty: "intermediate", definition: "Acid-base chemistry studies proton transfer and electron-pair interactions.", prerequisites: ["chemical-equilibrium"], relatedTerms: ["electrochemistry", "proteins"], formulaTex: "pH=-\\log_{10}[H^+]", example: "A buffer resists pH change by balancing a weak acid and its conjugate base." }),
  concept({ id: "electrochemistry", title: "Electrochemistry", subject: "Chemistry", difficulty: "advanced", definition: "Electrochemistry connects electron-transfer reactions with electric potential and current.", prerequisites: ["chemical-equilibrium", "electromagnetism"], relatedTerms: ["energy-storage", "thermodynamics"], formulaTex: "\\Delta G=-nFE", example: "A battery converts a spontaneous redox reaction into electrical work." }),
  concept({ id: "organic-chemistry", title: "Organic Chemistry", subject: "Chemistry", difficulty: "advanced", definition: "Organic chemistry studies carbon-containing structures, functional groups, and reaction mechanisms.", prerequisites: ["chemical-bonds", "chemical-kinetics"], relatedTerms: ["proteins", "drug-discovery"], example: "A nucleophile donates an electron pair to form a new bond." }),
  concept({ id: "quantum-chemistry", title: "Quantum Chemistry", subject: "Chemistry", difficulty: "advanced", definition: "Quantum chemistry applies quantum mechanics to electronic structure and molecular behavior.", prerequisites: ["quantum-mechanics", "chemical-bonds"], relatedTerms: ["materials-science", "linear-algebra"], formulaTex: "\\hat H\\Psi=E\\Psi", example: "Approximate electron orbitals to predict molecular geometry." }),
  concept({ id: "reaction-diffusion-chemistry", title: "Chemical Reaction-Diffusion", subject: "Chemistry", subjects: ["Chemistry", "Mathematics"], difficulty: "frontier", definition: "Chemical reaction-diffusion couples local reaction kinetics to spatial transport.", prerequisites: ["chemical-kinetics", "heat-equation"], relatedTerms: ["reaction-diffusion-biology", "stochastic-pdes"], formulaTex: "\\partial_t c=D\\nabla^2c+R(c)", example: "An oscillating reaction develops traveling concentration waves.", frontierExtensions: ["Oscillatory chemistry", "Autocatalytic fronts", "Nonequilibrium pattern formation"] })
];

export const economics = [
  concept({ id: "scarcity", title: "Scarcity and Choice", subject: "Economics", difficulty: "beginner", definition: "Scarcity means finite resources must be allocated among competing uses.", relatedTerms: ["opportunity-cost", "optimization"], example: "A city must divide a fixed budget among transit, schools, and housing." }),
  concept({ id: "opportunity-cost", title: "Opportunity Cost", subject: "Economics", difficulty: "beginner", definition: "Opportunity cost is the value of the best alternative forgone by a choice.", prerequisites: ["scarcity"], relatedTerms: ["consumer-theory", "expected-value"], formulaTex: "OC(a)=\\max_{b\\ne a}V(b)", example: "The cost of an hour-long meeting includes the best alternative use of that hour." }),
  concept({ id: "supply-demand", title: "Supply and Demand", subject: "Economics", difficulty: "beginner", definition: "Supply and demand describe how willingness to buy and sell interact to shape prices and quantities.", prerequisites: ["functions"], relatedTerms: ["elasticity", "market-structures"], formulaTex: "Q_d(P^*)=Q_s(P^*)", example: "A shortage pushes buyers to compete through higher prices." }),
  concept({ id: "elasticity", title: "Elasticity", subject: "Economics", difficulty: "intermediate", definition: "Elasticity measures the percentage response of one variable to a percentage change in another.", prerequisites: ["derivatives", "supply-demand"], relatedTerms: ["regression", "consumer-theory"], formulaTex: "\\varepsilon=\\frac{dQ}{dP}\\frac{P}{Q}", example: "Estimate how strongly demand changes after a price increase." }),
  concept({ id: "consumer-theory", title: "Consumer Theory", subject: "Economics", difficulty: "intermediate", definition: "Consumer theory models choices that maximize preferences subject to constraints.", prerequisites: ["opportunity-cost", "optimization"], relatedTerms: ["behavioral-economics", "game-theory"], formulaTex: "\\max_x u(x)\\ \\text{s.t.}\\ p\\cdot x\\le m", example: "Choose a basket of goods under a fixed budget." }),
  concept({ id: "firm-production", title: "Firms and Production", subject: "Economics", difficulty: "intermediate", definition: "Production theory models how firms transform inputs into outputs and costs.", prerequisites: ["functions", "opportunity-cost"], relatedTerms: ["optimization", "market-structures"], formulaTex: "\\pi(q)=R(q)-C(q)", example: "A firm chooses output where marginal revenue equals marginal cost." }),
  concept({ id: "market-structures", title: "Market Structures", subject: "Economics", difficulty: "intermediate", definition: "Market structure describes how competition, concentration, and entry affect behavior and outcomes.", prerequisites: ["supply-demand", "firm-production"], relatedTerms: ["game-theory", "antitrust"], example: "A monopolist faces different pricing incentives than a competitive firm." }),
  concept({ id: "game-theory", title: "Game Theory", subject: "Economics", difficulty: "advanced", definition: "Game theory studies strategic choices when each participant's outcome depends on others.", prerequisites: ["probability", "consumer-theory"], relatedTerms: ["reinforcement-learning", "mechanism-design"], formulaTex: "u_i(s_i^*,s_{-i}^*)\\ge u_i(s_i,s_{-i}^*)", example: "Competing firms may both cut prices even when both prefer higher margins." }),
  concept({ id: "externalities", title: "Externalities and Public Goods", subject: "Economics", difficulty: "advanced", definition: "Externalities occur when actions impose benefits or costs not captured by market prices.", prerequisites: ["supply-demand", "opportunity-cost"], relatedTerms: ["ecology", "mechanism-design"], formulaTex: "MSC=MPC+MEC", example: "Pollution creates health costs outside the producer's private accounting." }),
  concept({ id: "macroeconomics", title: "Macroeconomics", subject: "Economics", difficulty: "advanced", definition: "Macroeconomics studies aggregate output, inflation, unemployment, growth, and policy.", prerequisites: ["supply-demand", "firm-production"], relatedTerms: ["time-series", "causal-inference"], formulaTex: "Y=C+I+G+NX", example: "Analyze how interest-rate changes affect spending and inflation." }),
  concept({ id: "econometrics", title: "Econometrics", subject: "Economics", subjects: ["Economics", "Data Science"], difficulty: "advanced", definition: "Econometrics applies statistical models to economic questions and causal claims.", prerequisites: ["regression", "hypothesis-testing", "supply-demand"], relatedTerms: ["causal-inference", "time-series"], formulaTex: "y=X\\beta+\\varepsilon", example: "Estimate the effect of education on earnings while addressing confounding." }),
  concept({ id: "mechanism-design", title: "Mechanism Design", subject: "Economics", difficulty: "frontier", definition: "Mechanism design constructs rules so strategic behavior produces desired outcomes.", prerequisites: ["game-theory", "probability"], relatedTerms: ["distributed-systems", "cryptography"], formulaTex: "v_i(\\theta_i,x(\\theta_i)) - p_i(\\theta_i)\\ge v_i(\\theta_i,x(\\hat\\theta_i))-p_i(\\hat\\theta_i)", example: "Design an auction that encourages truthful bids.", frontierExtensions: ["Algorithmic mechanism design", "Market design", "AI alignment incentives"] })
];

export const dataScience = [
  concept({ id: "data-literacy", title: "Data Literacy", subject: "Data Science", difficulty: "beginner", definition: "Data literacy is the ability to interpret how data was generated, measured, summarized, and used.", prerequisites: ["measurement-units"], relatedTerms: ["data-visualization", "experimental-design"], example: "Ask what population and process produced a dashboard metric." }),
  concept({ id: "descriptive-statistics", title: "Descriptive Statistics", subject: "Data Science", difficulty: "beginner", definition: "Descriptive statistics summarize the center, spread, and shape of observed data.", prerequisites: ["numbers", "data-literacy"], relatedTerms: ["probability-distributions", "data-visualization"], formulaTex: "\\bar x=\\frac1n\\sum_{i=1}^n x_i", example: "Compare median and mean income when a few values are extremely large." }),
  concept({ id: "probability", title: "Probability", subject: "Data Science", subjects: ["Data Science", "Mathematics"], difficulty: "beginner", definition: "Probability provides a mathematical language for uncertainty and random events.", prerequisites: ["numbers"], relatedTerms: ["expected-value", "bayesian-inference"], formulaTex: "P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}", example: "Compute the chance of two independent component failures." }),
  concept({ id: "probability-distributions", title: "Probability Distributions", subject: "Data Science", difficulty: "intermediate", definition: "A probability distribution assigns probabilities or densities to possible outcomes.", prerequisites: ["probability", "integrals"], relatedTerms: ["sampling", "statistical-mechanics"], formulaTex: "\\int_{-\\infty}^{\\infty}p(x)\\,dx=1", example: "Use a normal distribution to model measurement noise." }),
  concept({ id: "sampling", title: "Sampling", subject: "Data Science", difficulty: "intermediate", definition: "Sampling selects observations from a population so properties of the population can be inferred.", prerequisites: ["probability-distributions", "data-literacy"], relatedTerms: ["hypothesis-testing", "experimental-design"], formulaTex: "SE(\\bar X)=\\frac{\\sigma}{\\sqrt n}", example: "Randomly sample voters instead of surveying only website visitors." }),
  concept({ id: "hypothesis-testing", title: "Hypothesis Testing", subject: "Data Science", difficulty: "intermediate", definition: "Hypothesis testing evaluates how surprising observed data would be under a specified null model.", prerequisites: ["sampling", "probability-distributions"], relatedTerms: ["experimental-design", "bayesian-inference"], formulaTex: "p=P(T\\ge T_{obs}\\mid H_0)", example: "Test whether an observed conversion-rate difference exceeds expected random variation." }),
  concept({ id: "regression", title: "Regression", subject: "Data Science", difficulty: "intermediate", definition: "Regression models how an outcome changes with one or more predictors.", prerequisites: ["linear-algebra", "probability-distributions"], relatedTerms: ["supervised-learning", "econometrics"], formulaTex: "\\hat\\beta=(X^TX)^{-1}X^Ty", example: "Relate house price to area, location, and age." }),
  concept({ id: "causal-inference", title: "Causal Inference", subject: "Data Science", difficulty: "advanced", definition: "Causal inference estimates what would happen under interventions by reasoning about counterfactuals.", prerequisites: ["regression", "experimental-design", "probability"], relatedTerms: ["econometrics", "systems-biology"], formulaTex: "\\operatorname{ATE}=E[Y(1)-Y(0)]", example: "Separate the effect of a feature from the fact that engaged users adopt it first." }),
  concept({ id: "time-series", title: "Time Series", subject: "Data Science", difficulty: "advanced", definition: "Time-series analysis models observations ordered through time, including trend, seasonality, and dependence.", prerequisites: ["probability-distributions", "regression"], relatedTerms: ["macroeconomics", "signal-processing"], formulaTex: "x_t=\\phi x_{t-1}+\\varepsilon_t", example: "Forecast electricity demand while accounting for daily cycles." }),
  concept({ id: "bayesian-inference", title: "Bayesian Inference", subject: "Data Science", difficulty: "advanced", definition: "Bayesian inference updates prior beliefs with evidence to produce posterior uncertainty.", prerequisites: ["probability", "probability-distributions"], relatedTerms: ["quantum-mechanics", "generative-models"], formulaTex: "p(\\theta\\mid D)=\\frac{p(D\\mid\\theta)p(\\theta)}{p(D)}", example: "Update the probability of a diagnosis after receiving a test result." }),
  concept({ id: "data-visualization", title: "Data Visualization", subject: "Data Science", difficulty: "beginner", definition: "Data visualization maps values to visual properties to support comparison, pattern recognition, and explanation.", prerequisites: ["data-literacy", "descriptive-statistics"], relatedTerms: ["human-computer-interaction", "sampling"], example: "Use position rather than area when precise comparison matters." }),
  concept({ id: "experimental-design", title: "Experimental Design", subject: "Data Science", difficulty: "advanced", definition: "Experimental design plans interventions, assignment, measurement, and analysis to support credible conclusions.", prerequisites: ["sampling", "hypothesis-testing"], relatedTerms: ["causal-inference", "measurement-units"], formulaTex: "\\hat\\tau=\\bar Y_T-\\bar Y_C", example: "Randomly assign users to product variants and predefine the success metric." }),
  concept({ id: "stochastic-processes", title: "Stochastic Processes", subject: "Data Science", subjects: ["Data Science", "Mathematics"], difficulty: "frontier", definition: "A stochastic process is a collection of random variables indexed by time or space.", prerequisites: ["probability-distributions", "time-series"], relatedTerms: ["stochastic-pdes", "reinforcement-learning"], formulaTex: "P(X_{t+1}\\mid X_t,\\ldots,X_0)=P(X_{t+1}\\mid X_t)", example: "Model a particle whose next movement includes a random component.", frontierExtensions: ["Martingales", "Gaussian processes", "Continuous-time inference"] })
];

export const machineLearning = [
  concept({ id: "supervised-learning", title: "Supervised Learning", subject: "Machine Learning", difficulty: "beginner", definition: "Supervised learning fits a mapping from inputs to labeled outcomes that should generalize to new data.", prerequisites: ["functions", "data-literacy"], relatedTerms: ["regression", "decision-trees"], formulaTex: "\\hat f=\\arg\\min_f\\sum_i L(f(x_i),y_i)", example: "Train a model to classify messages as spam or legitimate." }),
  concept({ id: "loss-functions", title: "Loss Functions", subject: "Machine Learning", difficulty: "intermediate", definition: "A loss function quantifies how costly a model's prediction error is.", prerequisites: ["supervised-learning", "functions"], relatedTerms: ["optimization", "expected-value"], formulaTex: "L(\\theta)=\\frac1n\\sum_{i=1}^n \\ell(f_\\theta(x_i),y_i)", example: "Squared error penalizes large numerical mistakes more strongly." }),
  concept({ id: "gradient-descent", title: "Gradient Descent", subject: "Machine Learning", subjects: ["Machine Learning", "Mathematics"], difficulty: "intermediate", definition: "Gradient descent iteratively changes parameters in the direction that reduces a differentiable loss.", prerequisites: ["derivatives", "multivariable-calculus", "loss-functions"], relatedTerms: ["neural-networks", "optimization"], formulaTex: "\\theta_{t+1}=\\theta_t-\\eta\\nabla_\\theta L(\\theta_t)", example: "Adjust a line's slope and intercept to reduce prediction error." }),
  concept({ id: "regularization", title: "Regularization", subject: "Machine Learning", difficulty: "intermediate", definition: "Regularization discourages overly complex solutions to improve generalization.", prerequisites: ["loss-functions", "probability"], relatedTerms: ["bayesian-inference", "neural-networks"], formulaTex: "L_{reg}(\\theta)=L(\\theta)+\\lambda\\|\\theta\\|_2^2", example: "Penalize very large coefficients so a model is less sensitive to noise." }),
  concept({ id: "decision-trees", title: "Decision Trees", subject: "Machine Learning", difficulty: "intermediate", definition: "Decision trees recursively partition data using feature-based rules.", prerequisites: ["supervised-learning", "probability"], relatedTerms: ["algorithms", "causal-inference"], formulaTex: "IG=H(Y)-\\sum_v P(v)H(Y\\mid v)", example: "Split loan applications by income and repayment history." }),
  concept({ id: "neural-networks", title: "Neural Networks", subject: "Machine Learning", difficulty: "advanced", definition: "Neural networks compose learned linear transformations and nonlinear activations into flexible functions.", prerequisites: ["linear-algebra", "gradient-descent", "regularization"], relatedTerms: ["gene-expression", "transformers"], formulaTex: "\\mathbf{h}_{l+1}=\\sigma(W_l\\mathbf{h}_l+\\mathbf{b}_l)", example: "Layers learn edges, textures, and shapes before recognizing an image." }),
  concept({ id: "convolutional-networks", title: "Convolutional Networks", subject: "Machine Learning", difficulty: "advanced", definition: "Convolutional networks use shared local filters to learn spatial patterns.", prerequisites: ["neural-networks", "fourier-analysis"], relatedTerms: ["computer-vision", "signal-processing"], formulaTex: "(f*g)(t)=\\int f(\\tau)g(t-\\tau)\\,d\\tau", example: "A learned filter responds to edges wherever they appear in an image." }),
  concept({ id: "transformers", title: "Transformers", subject: "Machine Learning", difficulty: "advanced", definition: "Transformers use attention to combine information across positions in a sequence.", prerequisites: ["neural-networks", "probability", "linear-algebra"], relatedTerms: ["language-models", "information-theory"], formulaTex: "\\operatorname{Attention}(Q,K,V)=\\operatorname{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V", example: "A word representation attends to earlier context that clarifies its meaning." }),
  concept({ id: "unsupervised-learning", title: "Unsupervised Learning", subject: "Machine Learning", difficulty: "advanced", definition: "Unsupervised learning discovers structure without explicit target labels.", prerequisites: ["probability-distributions", "linear-algebra"], relatedTerms: ["generative-models", "clustering"], formulaTex: "\\min_{C}\\sum_i\\min_{\\mu\\in C}\\|x_i-\\mu\\|^2", example: "Cluster customers by behavior without predefined segments." }),
  concept({ id: "reinforcement-learning", title: "Reinforcement Learning", subject: "Machine Learning", difficulty: "advanced", definition: "Reinforcement learning trains agents to choose actions that maximize long-term reward.", prerequisites: ["probability", "stochastic-processes", "game-theory"], relatedTerms: ["control-theory", "decision-making"], formulaTex: "Q^*(s,a)=E[r+\\gamma\\max_{a'}Q^*(s',a')]", example: "An agent learns a game strategy through rewards from repeated play." }),
  concept({ id: "generative-models", title: "Generative Models", subject: "Machine Learning", difficulty: "advanced", definition: "Generative models learn probability distributions that can produce new data-like samples.", prerequisites: ["bayesian-inference", "neural-networks", "unsupervised-learning"], relatedTerms: ["diffusion-models", "transformers"], formulaTex: "x\\sim p_\\theta(x)", example: "Generate a new image by sampling from a learned visual distribution." }),
  concept({ id: "diffusion-models", title: "Diffusion Models", subject: "Machine Learning", subjects: ["Machine Learning", "Mathematics", "Physics"], difficulty: "frontier", definition: "Diffusion models learn to reverse a gradual noising process and generate structured samples.", prerequisites: ["generative-models", "heat-equation", "stochastic-processes"], relatedTerms: ["stochastic-pdes", "thermodynamics"], formulaTex: "dx=-\\frac12\\beta(t)x\\,dt+\\sqrt{\\beta(t)}\\,dW_t", example: "Start from noise and repeatedly denoise toward a coherent image.", frontierExtensions: ["Flow matching", "Score-based SDEs", "Scientific diffusion models"] })
];

export const allConcepts = [
  ...mathematics,
  ...physics,
  ...computerScience,
  ...biology,
  ...chemistry,
  ...economics,
  ...dataScience,
  ...machineLearning
];

const conceptIds = new Set(allConcepts.map((item) => item.id));

for (const item of allConcepts) {
  item.relatedTerms = item.relatedTerms.filter((id) => conceptIds.has(id));
  item.prerequisites = item.prerequisites.filter((id) => conceptIds.has(id));
  item.deeperConcepts = allConcepts
    .filter((candidate) => candidate.prerequisites.includes(item.id))
    .map((candidate) => candidate.id);
}
